#ifndef __V4L2_AM_CONTEXT__
#define __V4L2_AM_CONTEXT__

#include <linux/videodev2.h>

#define AM_V4L2_SUB_EXT_VDEC_BASE (0x8000)

#define AM_V4L2_SUB_EXT_VDEC_FRAME (AM_V4L2_SUB_EXT_VDEC_BASE + 1)
#define AM_V4L2_SUB_EXT_VDEC_PICINFO (AM_V4L2_SUB_EXT_VDEC_BASE + 2)
#define AM_V4L2_SUB_EXT_VDEC_USERDATA (AM_V4L2_SUB_EXT_VDEC_BASE + 3)

/* Event types supported by vout adapter. */
#define AM_V4L2_SUB_EXT_VOUT_BASE                        (AM_V4L2_SUB_EXT_VDEC_USERDATA)
#define AM_V4L2_SUB_EXT_VOUT_AV_SYNC                (AM_V4L2_SUB_EXT_VOUT_BASE + 1)
#define AM_V4L2_SUB_EXT_VOUT_FRAME_ADVANCE                (AM_V4L2_SUB_EXT_VOUT_BASE + 2)
#define AM_V4L2_SUB_EXT_VOUT_DECODING_SPEED        (AM_V4L2_SUB_EXT_VOUT_BASE + 3)
#define AM_V4L2_SUB_EXT_VOUT_FREEZE_MODE                (AM_V4L2_SUB_EXT_VOUT_BASE + 4)
#define AM_V4L2_SUB_EXT_VOUT_STC_MODE                (AM_V4L2_SUB_EXT_VOUT_BASE + 5)
#define AM_V4L2_SUB_EXT_VOUT_AUDIO_CHANNEL                (AM_V4L2_SUB_EXT_VOUT_BASE + 6)
#define AM_V4L2_SUB_EXT_VOUT_DISPLAY_DELAY                (AM_V4L2_SUB_EXT_VOUT_BASE + 7)
#define AM_V4L2_SUB_EXT_VOUT_LIPSYNC_MASTER        (AM_V4L2_SUB_EXT_VOUT_BASE + 8)
#define AM_V4L2_SUB_EXT_VOUT_VSYNC_THRESHOLD        (AM_V4L2_SUB_EXT_VOUT_BASE + 9)


#define AM_V4L2_CID_USER_EXT_VSC_BASE (V4L2_CID_USER_BASE + 0x2000)
#define AM_V4L2_CID_USER_EXT_CAPTURE_BASE (V4L2_CID_USER_BASE + 0x2100)
#define AM_V4L2_CID_USER_EXT_PQ_BASE (V4L2_CID_USER_BASE + 0x3000)
#define AM_V4L2_CID_USER_EXT_VBE_BASE (V4L2_CID_USER_BASE + 0x4000)
#define AM_V4L2_CID_USER_EXT_HDMI_BASE (V4L2_CID_USER_BASE + 0x5000)
#define AM_V4L2_CID_USER_EXT_ADC_BASE (V4L2_CID_USER_BASE + 0x6000)
#define AM_V4L2_CID_USER_EXT_AVD_BASE (V4L2_CID_USER_BASE + 0x7000)
#define AM_V4L2_CID_USER_EXT_VDEC_BASE (V4L2_CID_USER_BASE + 0x8000)
// 0x9000 is being used by FE: see v4l2-ext-frontend.h
#define AM_V4L2_CID_USER_EXT_GPSCALER_BASE (V4L2_CID_USER_BASE + 0xA000)
#define AM_V4L2_CID_USER_EXT_EARC_BASE (V4L2_CID_USER_BASE + 0xB000)
#define AM_V4L2_CID_USER_EXT_VBI_BASE (V4L2_CID_USER_BASE + 0xC000)

#define AM_V4L2_CID_EXT_VDEC_BASE (AM_V4L2_CID_USER_EXT_VDEC_BASE + 0x0)
#define AM_V4L2_CID_EXT_VDEC_CHANNEL (AM_V4L2_CID_EXT_VDEC_BASE + 1)
#define AM_V4L2_CID_EXT_VDEC_VTP_PORT (AM_V4L2_CID_EXT_VDEC_BASE + 2)
#define AM_V4L2_CID_EXT_VDEC_RESETTING (AM_V4L2_CID_EXT_VDEC_BASE + 3)
#define AM_V4L2_CID_EXT_VDEC_VDO_PORT (AM_V4L2_CID_EXT_VDEC_BASE + 4)
#define AM_V4L2_CID_EXT_VDEC_AV_SYNC (AM_V4L2_CID_EXT_VDEC_BASE + 5)
#define AM_V4L2_CID_EXT_VDEC_FRAME_ADVANCE (AM_V4L2_CID_EXT_VDEC_BASE + 6)
#define AM_V4L2_CID_EXT_VDEC_DECODING_SPEED (AM_V4L2_CID_EXT_VDEC_BASE + 7)
#define AM_V4L2_CID_EXT_VDEC_DECODE_MODE (AM_V4L2_CID_EXT_VDEC_BASE + 8)
#define AM_V4L2_CID_EXT_VDEC_FREEZE_MODE (AM_V4L2_CID_EXT_VDEC_BASE + 9)
#define AM_V4L2_CID_EXT_VDEC_DECODER_VERSION (AM_V4L2_CID_EXT_VDEC_BASE + 10)
#define AM_V4L2_CID_EXT_VDEC_KR_DUAL_3D_MODE (AM_V4L2_CID_EXT_VDEC_BASE + 11)
#define AM_V4L2_CID_EXT_VDEC_STC_MODE (AM_V4L2_CID_EXT_VDEC_BASE + 12)
#define AM_V4L2_CID_EXT_VDEC_AUDIO_CHANNEL (AM_V4L2_CID_EXT_VDEC_BASE + 13)
#define AM_V4L2_CID_EXT_VDEC_DISPLAY_DELAY (AM_V4L2_CID_EXT_VDEC_BASE + 14)
#define AM_V4L2_CID_EXT_VDEC_LIPSYNC_MASTER (AM_V4L2_CID_EXT_VDEC_BASE + 15)
#define AM_V4L2_CID_EXT_VDEC_VSYNC_THRESHOLD (AM_V4L2_CID_EXT_VDEC_BASE + 16)
#define AM_V4L2_CID_EXT_VDEC_FAST_IFRAME_MODE (AM_V4L2_CID_EXT_VDEC_BASE + 17)
#define AM_V4L2_CID_EXT_VDEC_HFR_TYPE (AM_V4L2_CID_EXT_VDEC_BASE + 19)
#define AM_V4L2_CID_EXT_VDEC_TEMPORAL_ID_MAX (AM_V4L2_CID_EXT_VDEC_BASE + 20)

/* VDO class control ID */
#define AM_V4L2_CID_EXT_VDO_BASE (AM_V4L2_CID_USER_EXT_VDEC_BASE + 0x500)

#define AM_V4L2_CID_EXT_VDO_VDEC_PORT (AM_V4L2_CID_EXT_VDO_BASE + 1)
#define AM_V4L2_CID_EXT_VDO_VDEC_CONNECTING (AM_V4L2_CID_EXT_VDO_BASE + 2)
#define AM_V4L2_CID_EXT_VDO_VDEC_DISCONNECTING (AM_V4L2_CID_EXT_VDO_BASE + 3)

#define AM_V4L2_CID_EXT_CAPTURE_CAPABILITY_INFO (AM_V4L2_CID_USER_EXT_CAPTURE_BASE + 0)

#define AM_V4L2_CID_EXT_CAPTURE_PLANE_INFO (AM_V4L2_CID_USER_EXT_CAPTURE_BASE + 1)
#define AM_V4L2_CID_EXT_CAPTURE_VIDEO_WIN_INFO (AM_V4L2_CID_USER_EXT_CAPTURE_BASE + 2)
#define AM_V4L2_CID_EXT_CAPTURE_PLANE_PROP (AM_V4L2_CID_USER_EXT_CAPTURE_BASE + 3)
#define AM_V4L2_CID_EXT_CAPTURE_FREEZE_MODE (AM_V4L2_CID_USER_EXT_CAPTURE_BASE + 4)

#define AM_V4L2_EVENT_PRIVATE_EXT_VDEC_BASE (V4L2_EVENT_PRIVATE_START + 0x8000)

#define AM_V4L2_EVENT_PRIVATE_EXT_VDEC_EVENT (AM_V4L2_EVENT_PRIVATE_EXT_VDEC_BASE + 1)

struct am_v4l2_ext_vdec_vdo_connection {
    __u32 vdo_port;
    __u32 vdec_port;
};

#endif